[build]
  command = "cd ai-conference-2025 && npm install --legacy-peer-deps && npm run build && cd .. && cp -r Coaching_web Perfume_website Portfolio_website Startup_web ai-conference-2025/out/"
  publish = "ai-conference-2025/out"
