[build]
  command = "cd ai-conference-2025 && npm install --legacy-peer-deps && npm run build && cd .. && mkdir -p ai-conference-2025-built && cp -r ai-conference-2025/out/* ai-conference-2025-built/"
  publish = "."
